### ISSUE TITLE
mChat page weired text at "Who is chatting"

### ISSUE THREAD

**Issue by ghost** [dmzx/mChat-Extension#1]
I was testing mChat and saw that there come on the mChat page (not tested on index) after the reload this text ""\u003Cdiv class=\u0022mChatStats\u0022 id=\u0022mChatStats\u0022\u003E\u003Ca href=\u0022#\u0022 onclick=\u0022mChat.toggle(\u0027UserList\u0027); return false;\u0022\u003EIn total there is \u003Cstrong\u003E1\u003C\/strong\u003E user chatting \u003C\/a\u003E\u0026nbsp;based on users active over the past 5\u0026nbsp;minutes \u003Cbr \/\u003E\u003Cspan id=\u0022mChatUserList\u0022 style=\u0022display: none; float: left;\u0022\u003E\u003Ca href=\u0022.\/memberlist.php?mode=viewprofile\u0026amp;u=54\u0022 style=\u0022color: #dc2c49;\u0022 class=\u0022username-coloured\u0022\u003EMichel\u003C\/a\u003E\u003C\/span\u003E\u003C\/div\u003E"
".

**Comment by dmzx** [comment]
switch off for now the who is chatting in acp for mchat

**Comment by dmzx** [comment]
see version 0.0.3
