### ISSUE TITLE
A few language issues

### ISSUE THREAD

**Issue by leschek** [dmzx/mChat-Extension#10]
I wrote the post about those issues in phpBB.com (https://www.phpbb.com/community/viewtopic.php?f=456&t=2281451&start=210#p14010216), but I guess it get lost between the amount of posts in mChat topic, so I'm copying it here:
1. It seems that font sizes (in core phpBB) are replaced by strings in language file common.php in your extension.
2. I can't find in language file translation for "in" from sentence "Made A New Reply: ... in ...". I believe it is hard coded in file listener.php on line 142 (only part of line):

$event['post_data']['post_subject'] . '[/url] in [url=' . generate_board_url() . '/viewforum.' . $this->phpEx . '?f='
1. One more thing - I think lines in language file common.php:

'MCHAT_ONLINE_USERS_TOTAL'          => 'In total there are <strong>%d</strong> users chatting ',
    'MCHAT_ONLINE_USER_TOTAL'           => 'In total there is <strong>%d</strong> user chatting ',
should be in plural form.
1. in file styles/prosilver/template/mchat_ajax_mini.js is part of line 238 hardcoded (should be in language file):

apprise(mChatEditInfo + ' (Shift and Enter for new line)',{

EDIT: last two 1. and 1. should be 3. and 4.. Not sure why GitHub change it to 1. and 1.

**Comment by dmzx** [comment]
These will be solved in next version:    

```
in file styles/prosilver/template/mchat_ajax_mini.js is part of line 238 hardcoded (should be in language file):
```

apprise(mChatEditInfo + ' (Shift and Enter for new line)',{

I can't find in language file translation for "in" from sentence "Made A New Reply: ... in ...". I believe it is hard coded in file listener.php on line 142 (only part of line):

$event['post_data']['post_subject'] . '[/url] in [url=' . generate_board_url() . '/viewforum.' . $this->phpEx . '?f='

**Comment by leschek** [comment]
Thank you. Unfortunately I found another hardcoded word which should be in language file. In file event/listener.php on line 154 (version 0.0.12) is part:

$event['post_data']['forum_name'] . ' Section[/url] ');
The word section is hardcoded. 

For translators is easier to translate if the whole sentence with variables is on one line in language file.
For example now we have sentence: 

Made A Edit: Re: some topic in Your first forum section

on two lines in language file and without variables for topic name and forum.
I think it would be better if in language file is only one line with whole sentence. Something like this:

Made A Edit: %1$s in %2$s section

It's probably better explained in the "DEVELOPERS PLEASE NOTE" in language files.

EDIT: in file styles\prosilver\template\mchat_body.html
is another hardcoded part ('Like\'s this post):
.value += 'Like\'s this post.[quote="' + username + '"]'
