### ISSUE TITLE
Chat is not scrolling to the last post

### ISSUE THREAD

**Issue by jakubsuchybio** [dmzx/mChat-Extension#12]
Hi,
chat on the index page does not scroll down.
Dunno how to debug it or isn't it yet implemented?

Thx. Biosek

**Comment by dmzx** [comment]
This should be working

**Comment by jakubsuchybio** [comment]
Well we fixed it ourselfs with custom js. However, could you nagivate me where do you have this functionality in your extension? I Couldn't find it and maybe there is some wrong co-requisites with other extensions which I have installed.
