### ISSUE TITLE
Color Palette replace Index

### ISSUE THREAD

**Issue by ghost** [dmzx/mChat-Extension#22]
Hi, dear dev'!
When I try to display mchat on index, my index disappear and I only see this: 
![171225232](https://cloud.githubusercontent.com/assets/12981876/8269176/1b08e932-179f-11e5-94d0-86f4a0fe5c49.jpg)
Why? :(

**Comment by dmzx** [comment]
What style do you use ?
Delete this line https://github.com/dmzx/mChat-Extension/blob/master/styles/prosilver/template/mchat_body.html#L13 and see if it works.

dmzx

**Comment by ghost** [comment]
I use "Simplicity" of Artodia. And indeed, by removing this line, it works. 
But it's still an issue :3
