### ISSUE TITLE
incorect version in extension setting in ACP

### ISSUE THREAD

**Issue by leschek** [dmzx/mChat-Extension#26]
This is just a small thing. After update to mchat 0.1.1 I still have in mChat configuration in ACP shown "Version: 0.0.14"

**Comment by dmzx** [comment]
Did you delete data in ACP when you disabled the extension ?

**Comment by leschek** [comment]
No, but when I delete the data it will update extension number, because I basically will have to install the extension as a new one. 
After deleting data in ACP the extension number updated. 
Point is, admin shouldn't have to delete data to update the extension.

**Comment by dmzx** [comment]
To update the version the migration file needs to be reloaded.
see https://github.com/dmzx/mChat-Extension/blob/master/migrations/mchat_schema.php#L28

This can only be done by deleting the data in ACP.

**Comment by rmcgirr83** [comment]
You should simply have to disable the extension in the ACP, then upload the new files and re-enable which should force the migration files to run again.  That is if a new migration file was created.

**Comment by Galixte** [comment]
No new migration file created, only migration files have been updated: https://github.com/dmzx/mChat-Extension/commit/3a4ac22d8c7ec2a602c6e57e52ae04d481fd42c6.
