### ISSUE TITLE
Quick Menu on index bottom right corner not working if mChat enabled on index

### ISSUE THREAD

**Issue by DrDeath** [dmzx/mChat-Extension#27]
Hi,

I'm using the mChat 0.1.1 Extension.

I have a little issue:

The "Quick Menu" on the  bottom right corner on the index page is not working anymore in Responsive mode.

![Image of Quick Menu](http://lpi-clan.de/mchat_issue.png)

I'm using a prosilver style with darker colors, but the problem remain on standard prosilver.

If I disable the mChat on Index, the small Quick Menu is working again.

**Comment by DrDeath** [comment]
Same Bug on your own site: http://www.dmzx-web.net/index.php

Click on bottom right corner Quick Menu in Responive mode.
Nothing happens, if mChat is enabled on Index:

![mchat_on_index_bug_site_dmz](https://cloud.githubusercontent.com/assets/198929/9229396/446e8b04-411d-11e5-9e30-958caf2d069b.png)

**Comment by dmzx** [comment]
fixed

**Comment by DrDeath** [comment]
Confirmed. Thank you!
