### ISSUE TITLE
jQuery duplicity issue

### ISSUE THREAD

**Issue by jakubsuchybio** [dmzx/mChat-Extension#4]
Hi,
could you please move jquery include from footer to the custom page where mchat is running? (Later only into index page, when mchat will be embedded into index page)

Because we are using jQuery in our custom pages, but in different version and it makes errors and some functionality of our custom pages is lost, etc :)

Thank you!
Biosek

**Comment by dmzx** [comment]
changed in version 0.0.4

**Comment by ovitrif** [comment]
Could you please load jQuery where all other themes load scripts? Right now it breaks Bootstrap's JavaScript on my forum theme because it loads an older version of jQuery. 

Also, why would an extension load jQuery by itself when phpBB is already configured to load it?
