### ISSUE TITLE
0.3.2 - Controller Error - Missing return parameter

### ISSUE THREAD

**Issue by DrDeath** [dmzx/mChat-Extension#40]
Click the button "Purge" in the mChat on index  (MCHAT_CLEAN)
You will receive a confirmation popup. "Remove all messages?"  (MCHAT_DELALLMESS)
Click "NO" 

Error message from controller:

Information

The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?

**Comment by kasimi** [comment]
Thanks, this will be fixed in the next version.

**Comment by DrDeath** [comment]
Hi, I think this report is obsolete now.... in RC-1 there is no "prune" button anymore :-)

**Comment by dmzx** [comment]
Its moved to ACP settings

**Comment by DrDeath** [comment]
Yes, that's ok.
Thats the reason we could close this Issue here.
