### ISSUE TITLE
Wrong forum link for new post notification

### ISSUE THREAD

**Issue by papermate** [dmzx/mChat-Extension#41]
There is an extra %20 in the forum link, just before the .php
For example:
`http://forum.test.com/viewforum.%20php?f=14`
INSTEAD OF 
`http://forum.test.com/viewforum.php?f=14`

**Comment by kasimi** [comment]
This has already been fixed in 0.3.3. Do you have this problem in 0.3.3 or in an earlier version?

**Comment by dmzx** [comment]
papermate what version do you use?

**Comment by papermate** [comment]
Thanks for answering, I am using 0.3.2, I'll report back in case I have the same problem in the 0.3.3
