### ISSUE TITLE
Can't change options after update

### ISSUE THREAD

**Issue by papermate** [dmzx/mChat-Extension#43]
Hello all, I just installed the 1.o RC1, but after the install I can't just the options from the admin panel and a script keeps looping until it reaches the critical level and mozilla makes it stop.
I tried chmodding the mchat folder recursevely in 775, no good.

Any help?

**Comment by dmzx** [comment]
Did you delete data in ACP when unstalling previous version?

**Comment by papermate** [comment]
That was it, it did the trick, thanks!

Just a report, the default avatar is displayed in a 1:1 size in the chat now, it's not scaled down like the set ones are. It's huge.

Thanks again for your help

**Comment by kasimi** [comment]
@papermate What browser are you using? What are the avatar's width and height? Did you try to empty both the phpBB cache and your browser's cache?

**Comment by papermate** [comment]
@kasimi I use Mozilla Firefox (Iceweasel).
I've emptied both phpbb and browser cache and the default avatar size is 100x100 (no_avatar.gif, the default one), and is displayed in full size in the chat. All the set ones are displayed resized.
Maybe I should open a separate issue.

Thanks for your time

**Comment by kasimi** [comment]
Sounds like an issue with your CSS. Please verify that your `/ext/dmzx/mchat/styles/prosilver/theme/mchat.css` file is up to date and contains [these rules ](https://github.com/dmzx/mChat-Extension/commit/560ab2ee81a71283be4cf0834c1dcc4560b293cb#diff-86342e769d974e08a8f955ef9a31d7dd) for the `.mchat-avatar` class and that it is correctly served to your browser.

If this doesn't help opening a new issue is a good idea. :innocent:
