### ISSUE TITLE
Incompatible with newer Bootstrap versions

### ISSUE THREAD

**Issue by ovitrif** [dmzx/mChat-Extension#47]
Could you please load jQuery where all other themes load scripts? Right now it breaks Bootstrap's JavaScript on my forum theme because it loads an older version of jQuery.

Also, why would an extension load jQuery by itself when phpBB is already configured to load it?

**Comment by kasimi** [comment]
mChat does not include jQuery. It expects jQuery to be loaded at the time [mchat.js](https://github.com/dmzx/mChat-Extension/blob/master/styles/all/template/javascript/mchat.js) is executed, which is exactly the case for the prosilver style.

As far as I remember there was a very early DEV version of mChat that did in fact include its own copy of jQuery. You might be running an outdated version.

**Comment by ovitrif** [comment]
Thanks for the quick explanation. Sorry to bother :)
It was for a customer, and most probably he still uses an old version.

Keep up the good work!

PS: great work :+1:
