### ISSUE TITLE
SQL error during extension activation

### ISSUE THREAD

**Issue by hktr92** [dmzx/mChat-Extension#49]
Hello!

I downloaded the latest mchat version, 2.0.0-RC5, from [phpBB forum](https://www.phpbb.com/community/viewtopic.php?f=456&t=2281451), and when I hit `enable` link in ACP, an error was thrown (image below).

![screenshot_20160724_144516](https://cloud.githubusercontent.com/assets/7689151/17083558/c3d93b68-51ad-11e6-8a41-9e7f559e52c5.png)

**Comment by kasimi** [comment]
Uninstall the extension, delete the data, apply this fix and install again: https://www.phpbb.com/community/viewtopic.php?p=14467096#p14467096
