### ISSUE TITLE
Dissepear

### ISSUE THREAD

**Issue by Hitwalker** [dmzx/mChat-Extension#5]
When i enable mChat on index my nivo slider dissepear?

**Comment by dmzx** [comment]
check if there are double .js files active

**Comment by Hitwalker** [comment]
it seems to be 1 of each

**Comment by dmzx** [comment]
see http://www.dmzx-web.net/viewtopic.php?p=1825#p1825

**Comment by Hitwalker** [comment]
Hmmm...that code does work when you have mChat enable don't you have it does not nivoslider work...did see cece74 changed code nivo slider will probly not work with out mchat
